### ISSUE TITLE
Does it need modifications for 64-bit OpenFOAM?

### ISSUE THREAD

**Issue by venugopalansgr** [ITHACA-FV/ITHACA-FV#304]
Hi,

I was testing ITHACA-FV with OpenFOAM-v1812. I was having issues with compiling the package. And most of the error seemed to be **int vs. label**. Mine is WM_LABEL_SIZE of 64.

Does it currently only support WM_LABEL_SIZE of 32?

I managed to play around (changing label and int as needed) and get most of the compilation errors out of the way. But some seem more complex - like msrProblem.C under ITHACA_FOMPROBLEMS.

One of the error message at msrProblem.C was this: "Error: cannot bind non-const lvalue reference of type ‘int&’ to an rvalue of type ‘int’ "

Cheers,
venugopalansgr

**Comment by olesenm** [comment]
The code should be using `label` instead of `int` in most places.

**Comment by giovastabile** [comment]
@venugopalansgr I will have a look at the issue. We never tried to compile with WM_LABEL_SIZE of 64. @olesenm thanks for the hint, we will replace int with label in the next PR.

**Comment by giovastabile** [comment]
@venugopalansgr which is the line of code which is causing trouble?

**Comment by venugopalansgr** [comment]
Hi @giovastabile,

So the file where I encountered the "cannot bind non-const lvalue..." error (and decided to raise the issue here) is from **msrProblem.C**. Specifically, the error pops up at **line 502** in the same file.

Apart from that there are other errors which relate to int vs. label in the same **msrProblem.C** file. These happen at **lines 1077, 1128 and 1149** of the file. Hence ITHACA_FOMPROBLEMS did not compile

Also, the other files where I temporarily made changes to get it to compile are in:
1. **ITHACA_CORE/ITHACAparallel**. Here I made changes to the type for oldProcIDs_ and newProcIDs_ since OpenFOAM's Pstream::procID(comms) returns int as opposed to label (based on OpenFOAM's Pstream.H/Pstream.C files)

2. **ITHACA_CORE/ITHACAutilities/ITHACAgeometry**. Here there were a few changes made again according to whether it was int or label (to make it consistent)

3. **ITHACA_DEIM/DEIM.C**. Here there were a few changes made again according to whether it was int or label (to make it consistent)

These are definitely not the cleanest/nicest/most efficient modifications, but I could overcome the compiler issues and get ITHACA_CORE and ITHACA_DEIM to compile. No luck yet with ITHACA_FOMPROBLEMS though.

Cheers,
venugopalansgr

**Comment by giovastabile** [comment]
Ok I think that if you replace everywhere in the file int with label it should work fine. You will have to change also the declaration of the msrcoeff function both in the H and in the C files.

**Comment by olesenm** [comment]
> We never tried to compile with WM_LABEL_SIZE of 64. @olesenm thanks for the hint, we will replace int with label in the next PR.

To be extra safe, I would recommend the following:
```
# label-size=64 scalar-size=32 solvescalar-size=64
export WM_LABEL_SIZE=64
export WM_PRECISION_OPTION=SPDP

# Use system Clang100 as well
export WM_COMPILER_TYPE=system
export WM_COMPILER=Clang100
```

This catches various places with 64/32-bit and float/double issues. The clang compiler is a bit fussier about constructors than most gcc versions. You'll notice that I use clang-10.0 as a _system_ compiler. On openSUSE, it's available from the open build system.

To complete things, you can add in this type of make rule:
```
# Override compiler calls for llvm-10
ifeq ($(WM_COMPILER_TYPE),system)
    cc      = clang-10
    CC      = clang++-10 -std=c++11
endif
```
`wmake/rules/linux64Clang100/general` or `wmake/rules/linux64Clang/general` might be a good place for it.

**Comment by giovastabile** [comment]
@olesenm thanks, in the next days I will try all the different combinations. In the meanwhile, I changed label with int in all the places where it could have caused an issue. From my understanding, the issue was in the implicit conversion of an int to a label in the case of WM_LABEL_SIZE=64. @venugopalansgr please try to recompile everything after the last modifications to the library.

**Comment by olesenm** [comment]
Other (non-obvious) things to watch out for:
```
scalar /* float */ val = ...;
if (equal(val, 1.0))
```
Can have resolution problems between float/double, so better to write the `1.0` as `1` and allow integer promotion do things.

**Comment by venugopalansgr** [comment]
@giovastabile: Is there an update that you are referring to for this? Or just the modifications that I have been doing?
> @venugopalansgr please try to recompile everything after the last modifications to the library. 

To maintain consistency, I can restart with a fresh copy of ITHACA-FV and go from there. I can try and use @olesenm 's instructions as well...

**Comment by giovastabile** [comment]
@venugopalansgr I just pushed some modifications that should have fixed most of the issues that you were facing. If you start with a fresh new copy most of the problems should have been resolved.

Giovanni

**Comment by venugopalansgr** [comment]
Hi Giovanni,

I tried again just now - cloned the master/default repo and tried to compile. Still have issues and unable to compile. Weirdly most are still about the int/label issue. Is there a different version I should download instead?

Also, I think the int to label won't work everywhere. For example like the ITHACAparallel one which I have mentioned previously...

For ease of reference, I am attaching the log of the compile process:

[log.v1812_WM_LABEL_64.txt](https://github.com/mathLab/ITHACA-FV/files/5339372/log.v1812_WM_LABEL_64.txt)

Cheers,
venugopalansgr

**Comment by olesenm** [comment]
Makes sense. MPI ranks are `int`, not `long`

**Comment by giovastabile** [comment]
@venugopalansgr I am checking the issue right now and doing some testing. I will soon upload a version that is compatible with both WM_LABEL=32 and WM_LABEL=64.

**Comment by giovastabile** [comment]
@venugopalansgr the PR that I just merged should be ok. Please check it as well and let me know.

**Comment by venugopalansgr** [comment]
Hi @giovastabile,

I downloaded the latest and managed to compile the library, tutorials and applications with no problem. I also quickly ran the first tutorial case to make sure it runs - it did. No errors reported. 👍 

I'll close the issue since it has been sorted. Thanks! 👍 

Cheers,
Venugopalan
